spring:
  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
  h2:
    console:
      enabled: true
  liquibase:
    change-log: db/changelog/changelog.xml
  jpa:
    open-in-view: false
